# Generated by Django 5.1.2 on 2024-12-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author1',
            field=models.CharField(default=111, max_length=100),
            preserve_default=False,
        ),
    ]
