# Generated by Django 5.1.2 on 2024-12-03 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_author1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='author1',
            new_name='author',
        ),
    ]
