# Generated by Django 5.1.2 on 2024-12-04 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_myapp_blog_delete_book'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='myapp_blog',
            new_name='blog',
        ),
    ]
